# Orb 'circleci/node@1.1.6' resolved to 'circleci/node@1.1.6'
version: 2.1
orbs:
  heroku: circleci/heroku@1.0.1
jobs:
  build-and-test:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-deps-v1-{{ .Branch }}-{{ checksum "package.json" }}
            - node-deps-v1-{{ .Branch }}
            - node-deps-v1     
      - run:
            name: Download cc-test-reporter
            command: |
                mkdir -p tmp/
                curl - L  https://codeclimate.com/downloads/test-reporter/test-repo
                chmod +x ./tmp/cc-test-reporter
      - persist to workspace:
            root: tmp
            paths: 
                - cc-test-reporter             
      - run:
          command: npm install
      - run:
          command: | 
            npm test
            ./tmp/cc-test-reporter format-coverage -t lcov -o tmp/coodeclimate.backend.resultset.json
     

      - run:
          command: cd frontend && npm install && npm build && npm test &&  ./tmp/cc-test-reporter format-coverage -t lcov -o tmp/coodeclimate.frontend.resultset.json
 
      - persist_to_workspace:
            root: tmp
            paths: 
               - codeclimate.backend.json      
               - codeclimate.frontend.json
      - run: npm start & ./node_modules/.bin/cucumber-js
      - save_cache:
          key: node-deps-v1-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ~/project/node_modules
  upload-coverage:
    <<: *defaults
    environment:
        - CC_TEST_REPORTER_ID:
    steps: 
        - attach-workspace:
            at: ~/repo/tmp
        - run: 
            name: Upload test coverage results to Code Climate
            command: |   
                ./tmp/cc-test-reporter sum-coverage tmp/codeClimate.*.json - p 2 -o tmp/codeclimate.total.json
                ./tmp/cc-test-reporter upload-coverage -i tmp/codeclimate.total.json   
  

workflows:
  build-and-test:
    jobs:
      - build-and-test
  heroku_deploy:
    jobs:
      - build-and-test
      - heroku/deploy-via-git:
          requires:
            - build-and-test
          filters:
            branches:
              only: master
          app-name: "tip-library"

  version: 2
