# Orb 'circleci/node@1.1.6' resolved to 'circleci/node@1.1.6'
version: 2.1
orbs:
  heroku: circleci/heroku@1.0.1
jobs:
  build-and-test:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-deps-v1-{{ .Branch }}-{{ checksum "package.json" }}
            - node-deps-v1-{{ .Branch }}
            - node-deps-v1
      - run:
          command: npm install
      - run:
          command: npm test
      - save_cache:
          key: node-deps-v1-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ~/project/node_modules

workflows:
  build-and-test:
    jobs:
      - build-and-test
  heroku_deploy:
    jobs:
      - build-and-test
      - heroku/deploy-via-git:
          requires:
            - build-and-test
          filters:
            branches:
              only: master
  version: 2
